---
version: '2'

services:

  front:
    image: grizmin/nginx-proxy:$VERSION
    restart: always
    env_file: .env
    ports:
    - "$BIND_ADDRESS4:80:80"
    - "$BIND_ADDRESS4:443:443"

    volumes:
      - "$ROOT/certs:/certs:rw"
      - "$ROOT/nginx:/etc/nginx:rw"
      - "$ROOT/logs:/logs:rw"